name: Verify
on:
- push
- pull_request
permissions:
  checks: write
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          maven-version: 3.9.9
      - name: Install window manager
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y dbus-daemon xvfb mutter
      - name: Run Maven
        run: dbus-run-session -- xvfb-run -a -s "-screen 0 1024x768x24 -noreset" mvn -P linux --errors --batch-mode --no-transfer-progress -Dlicensecheck.skip=true clean verify
      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: maven_results
          include-hidden-files: true
          path: |
            **/target/work/**/*.log
            **/target/work/**/*.info
            **/target/work/**/*.ini
            **/target/results/**
            **/*.hrpof
            tests/*/target/*-reports/*.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v6.0.0
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/*-reports/*.xml'
          fail_on_failure: true
          annotate_only: true
      - name: Archive Linux server
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: server_linux
          path: 'products/products/target/products/org.eclipse.rcptt.cloud.server.product-linux.gtk.x86_64.zip'
      - name: Archive Windows agent
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: agent_windows
          path: 'products/products/target/products/org.eclipse.rcptt.cloud.agent.product-win32.win32.x86_64.zip'
